---
dev_name: stemcell_post_install
latest_release_filename: "/Users/mattcui/Developer/go_workspace/src/github.com/mattcui/stemcell-post-install/dev_releases/stemcell_post_install/stemcell_post_install-0.0.1.yml"
